### ISSUE TITLE
move analysis code from HNN GUI to start hnn_core.analysis submodule

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#139]
**Purpose:**
To make code that was previously only in [HNN GUI](https://github.com/jonescompneurolab/hnn) dual-purpose and serve for the analysis of simulations run by `hnn-core` from the command-line.

**Rationale:**
Since HNN GUI will import `hnn-core` already for `hnn_core.simulator` to run the NEURON solver, this will be a better home for the analysis functions. These functions will benefit from documentation and unit testing as part of `hnn-core`

**Proposed components:**
- [ ] Simulated LFP in `hnn_core.simulator` (#150)
- [ ] CSD calculation and plotting (#68)
- [ ] Objective functions for model optimization (parts from #77)
- [ ] Wrappers for parameter estimation with SNPE
- [ ] Spectral analysis
- [ ] RMSE calculation to data (#83 - closed, needs PR)

In addition to moving the code, the following improvments will be made:
 * Code cleanup (Use library functions, formatting, etc.)
 * Unit testing
 * Documentation

**Comment by blakecaldwell** [comment]
It's not clear whether optimization code should go entirely in analysis, or the wrapper that runs code in `hnn_core.simulator` should also go in `hnn_core.simulator`.

**Comment by jasmainak** [comment]
@blakecaldwell can you cross-link to already open pull requests and issues? For e.g., for `rmse` we already have a pull request and also for LFP/CSD.

**Comment by ntolley** [comment]
Going through the list all of these have actually been implemented in some capacity!
