### ISSUE TITLE
parallelization progress

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#141]
This issue is for keeping track of parallelization discussion and progress

- [ ] MPI as alternative to joblibs #78 
- [ ] print simulation progress message to MPIBackend #112 
- [ ] multiple trials with consistent seeding #113 
- [ ] issue related to codepaths

**Comment by blakecaldwell** [comment]
How much of a priority is combined MPI + Joblibs? It should work...

**Comment by jasmainak** [comment]
not super high priority for me, but if it works then that's great!

**Comment by cjayb** [comment]
What would be the use-case? Running 2 trials concurrently in two rank-8 MPI contexts on a 16-core desktop machine? Seems like an edge case?

**Comment by blakecaldwell** [comment]
Perhaps optimizing average dipole by running 3-trials on a 24-core machine. Mainak suggested this in the past. I think the benefit is very small over just using MPIBackend on a 24-core system (or however many cores).
