### ISSUE TITLE
release 0.2

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#365]
hi guys,

I think it's [time for another release](https://en.wikipedia.org/wiki/Release_early,_release_often). 3 month cycles are usually recommended but 6 months is also fine. I'd like to get it out before getting busy with next grant cycle. I'm thinking that these are the goals for this release:

## Priorities

- [x] finish average dipoles PR #368  @kenloi 
- [x] finish beta erp with Law 2019 model #348  @ntolley 
- [x] LFP #329  @cjayb
- [x] internal data containers: list to numpy when possible #358 @cjayb and @ntolley 
- [x] calcium dynamics #333 @ntolley 
- [x] can we close #330? we need to check that Neuron indeed adjusts `L` to match points. But also make sure our `L` and `sec_pts` agree! @cjayb 
- [x] Check that #262 can be closed (no use of implicit post-processing in our examples, perhaps set `postproc=False` as default in `simulate_dipole` @cjayb 
- [x] #315 ... I am actually stuck on this one. It's fiendishly difficult and low reward but must be done for the long run. Any help is really appreciated @jasmainak 
- [x] optimization PR #77 (doesn't use drives API yet) @jasmainak 
- [x] LFP follow-up: create API for setting in-plane cell distance #370 (finalise after #333)

## Connectivity API
- [x] Add `.drop(probability, src_gids, target_gids)` `.plot`
- [x] Function to search for specific connections in `net.connectivity` list: `conns = pick_connecitivity(conns, src=‘L2_pyramidal')` 
- [x] Viz function that plots connections weights with color bar as `plot_connectivity(net, conn)`
- [x] Merge the functions used for drives and cell-cell connections. This is partially done as everything is funneled through net.add_connection, but the next step is allowing the drives to target specific gids in a similar API #369 
~- Make `_Connectivity` a proper class with public and private attributes~
- [x] Pass probability argument to drives allowing for inputs to subsets of cells #416 

## Bump to 0.3

- The "baseline renormalisation" issue still freaks the bejeez' out of me (#220). The ad hoc fix I proposed in #270 isn't the right way to go. We have to dig deeper in the mechanism files to figure out which of them have massive initialisation transients (only L5, not L2)
- dealing with #234 and #244 @cjayb 

anything else? It's going to be a bombshell of a release!

**Comment by cjayb** [comment]
Made some edits/proposals. Perhaps need to prioritise... ;)

**Comment by ntolley** [comment]
I'd be interested in taking up the calcium dynamics. I am already laying the groundwork with #348 which is nearing completion (just need to take an afternoon and play with the simulations). 

I have also made a lot of progress on what is likely the most difficult task remaining for the connectivity API #367. 

The remaining stuff for more verbose warnings might be a good exercise for @kenloi as a more intermediate level PR. This would involve creating a list of what is considered "valid connections" (example, pyramidal cells shouldn't make GABA synapses), and referencing that list from `net.add_connection`.

**Comment by jasmainak** [comment]
@rythorpe any issues that are close to your heart and/or you'd want to tackle? we're thinking of an august release

**Comment by ntolley** [comment]
Something that's been on my mind for awhile, do you guys thinks it'd be possible to add a sentence or two to the main hnn-core page? At the moment it is extremely cryptic and requires you to go the HNN-GUI repo to figure out that this is a simulator for a neocortical column.

Perhaps

> This is a leaner and cleaner version of the code based off the HNN repository, a user friendly tool for the biophysical simulation of a neocortical column. However, a Graphical User Interface is not supported at the moment in this repository.


I can open a PR if you guys agree. Perhaps later it'd also be great to have a picture of the model there as well to make it immediately clear what this repo is for.

**Comment by jasmainak** [comment]
yes, that's fine! PR is welcome :)

**Comment by jasmainak** [comment]
okay, I checked some boxes and reordered the issues so it's clearer to what's done and what's left. Expanded the connectivity checklist so it's clear to see what needs to be done there. This issue has also been pinned so it's on top of the priority list.
